# Generated by Django 4.2.3 on 2023-07-24 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0008_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'verbose_name_plural': 'Venta de Vehículos'},
        ),
    ]
