# Generated by Django 4.2.3 on 2023-07-24 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0009_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': (('visualizar_catalogo', 'visualizar_catalogo'),), 'verbose_name_plural': 'Venta de Vehículos'},
        ),
    ]
